modLoader="javafml"
loaderVersion="[38,)"
license="MIT"

[[mods]]
modId="apples"
version="1.2"
displayName="Apples & Carrots"

logoFile="icon.png"
authors="agorasim20"
description='''
Special Apples and Carrots with effects

Hope you enjoy this adventure!
<3

Home: https://www.curseforge.com/minecraft/mc-mods/apples-carrots-forge
'''

[[dependencies.apples]]
    modId="forge"
    mandatory=true
    versionRange="[38,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.apples]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"