package agorasim20.apples.mod.items;

import agorasim20.apples.mod.ModMain;

import net.minecraft.world.effect.MobEffectInstance;
import net.minecraft.world.effect.MobEffects;
import net.minecraft.world.food.FoodProperties;
import net.minecraft.world.item.Item;
import net.minecraftforge.fmllegacy.RegistryObject;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;

public class ItemsRegistry {
    public static final DeferredRegister<Item> ITEMS_R = DeferredRegister.create(ForgeRegistries.ITEMS, "apples");

    private static final float tier1 = 1.8f;
    private static final float tier2 = 2f;
    private static final float tier3 = 2.5f;

    public static final RegistryObject<Item> COAL_APPLE = ITEMS_R.register("coal_apple", () -> new Item(new Item.Properties().tab(ModMain.CREATIVE_TAB).food(new FoodProperties.Builder().nutrition(8).alwaysEat().saturationMod(tier1).effect(() -> new MobEffectInstance(MobEffects.NIGHT_VISION, 1200), 1).effect(() -> new MobEffectInstance(MobEffects.DIG_SPEED, 800, 2), 1).build())));
    public static final RegistryObject<Item> COPPER_APPLE = ITEMS_R.register("copper_apple", () -> new Item(new Item.Properties().tab(ModMain.CREATIVE_TAB).food(new FoodProperties.Builder().nutrition(8).alwaysEat().saturationMod(tier1).effect(() -> new MobEffectInstance(MobEffects.MOVEMENT_SPEED, 1200, 2), 1).effect(() -> new MobEffectInstance(MobEffects.WEAKNESS, 100), 1).build())));
    public static final RegistryObject<Item> EMERALD_APPLE = ITEMS_R.register("emerald_apple", () -> new Item(new Item.Properties().tab(ModMain.CREATIVE_TAB).food(new FoodProperties.Builder().nutrition(8).alwaysEat().saturationMod(tier1).effect(() -> new MobEffectInstance(MobEffects.HERO_OF_THE_VILLAGE, 400), 1).effect(() -> new MobEffectInstance(MobEffects.HEALTH_BOOST, 800), 1).build())));
    public static final RegistryObject<Item> LAPIS_APPLE = ITEMS_R.register("lapis_apple", () -> new Item(new Item.Properties().tab(ModMain.CREATIVE_TAB).food(new FoodProperties.Builder().nutrition(9).alwaysEat().saturationMod(tier2).effect(() -> new MobEffectInstance(MobEffects.LUCK, 600), 1).effect(() -> new MobEffectInstance(MobEffects.DAMAGE_RESISTANCE, 1200), 1).build())));
    public static final RegistryObject<Item> OBSIDIAN_APPLE = ITEMS_R.register("obsidian_apple", () -> new Item(new Item.Properties().tab(ModMain.CREATIVE_TAB).food(new FoodProperties.Builder().nutrition(9).alwaysEat().saturationMod(tier1).effect(() -> new MobEffectInstance(MobEffects.DAMAGE_BOOST, 600, 0), 1).effect(() -> new MobEffectInstance(MobEffects.DAMAGE_RESISTANCE, 1800, 0), 1).effect(() -> new MobEffectInstance(MobEffects.WATER_BREATHING, 200), 1).effect(() -> new MobEffectInstance(MobEffects.FIRE_RESISTANCE, 200), 1).build())));
    public static final RegistryObject<Item> DIAMOND_APPLE = ITEMS_R.register("diamond_apple", () -> new Item(new Item.Properties().tab(ModMain.CREATIVE_TAB).food(new FoodProperties.Builder().nutrition(14).alwaysEat().saturationMod(tier3).effect(() -> new MobEffectInstance(MobEffects.REGENERATION, 1800, 2), 1).effect(() -> new MobEffectInstance(MobEffects.DAMAGE_BOOST, 1200, 1), 1).effect(() -> new MobEffectInstance(MobEffects.WATER_BREATHING, 2400), 1).effect(() -> new MobEffectInstance(MobEffects.HEALTH_BOOST, 1200, 1), 1).effect(() -> new MobEffectInstance(MobEffects.DAMAGE_RESISTANCE, 2400, 4), 1).build())));
    public static final RegistryObject<Item> NETHERITE_APPLE = ITEMS_R.register("netherite_apple", () -> new Item(new Item.Properties().tab(ModMain.CREATIVE_TAB).fireResistant().food(new FoodProperties.Builder().nutrition(20).alwaysEat().saturationMod(tier3).effect(() -> new MobEffectInstance(MobEffects.REGENERATION, 2400, 4), 1).effect(() -> new MobEffectInstance(MobEffects.DAMAGE_BOOST, 1800, 2), 1).effect(() -> new MobEffectInstance(MobEffects.FIRE_RESISTANCE, 2400), 1).effect(() -> new MobEffectInstance(MobEffects.HEALTH_BOOST, 2400, 2), 1).effect(() -> new MobEffectInstance(MobEffects.DAMAGE_RESISTANCE, 4800, 4), 1).build())));
    public static final RegistryObject<Item> IRON_APPLE = ITEMS_R.register("iron_apple", () -> new Item(new Item.Properties().tab(ModMain.CREATIVE_TAB).food(new FoodProperties.Builder().nutrition(9).alwaysEat().saturationMod(tier2).effect(() -> new MobEffectInstance(MobEffects.ABSORPTION, 800, 0), 1).effect(() -> new MobEffectInstance(MobEffects.REGENERATION, 800, 0), 1).effect(() -> new MobEffectInstance(MobEffects.DAMAGE_RESISTANCE, 2400), 1).build())));
    public static final RegistryObject<Item> CREATIVE_APPLE = ITEMS_R.register("creative_apple", () -> new Item(new Item.Properties().tab(ModMain.CREATIVE_TAB).food(new FoodProperties.Builder().nutrition(20).alwaysEat().saturationMod(tier3).effect(() -> new MobEffectInstance(MobEffects.REGENERATION, 4800, 9), 1).effect(() -> new MobEffectInstance(MobEffects.DAMAGE_BOOST, 4800, 9), 1).effect(() -> new MobEffectInstance(MobEffects.FIRE_RESISTANCE, 4800), 1).effect(() -> new MobEffectInstance(MobEffects.WATER_BREATHING, 4800), 1).effect(() -> new MobEffectInstance(MobEffects.HEALTH_BOOST, 4800, 4), 1).effect(() -> new MobEffectInstance(MobEffects.DAMAGE_RESISTANCE, 4800, 9), 1).build())));

    public static final RegistryObject<Item> COAL_CARROT = ITEMS_R.register("coal_carrot", () -> new Item(new Item.Properties().tab(ModMain.CREATIVE_TAB).food(new FoodProperties.Builder().nutrition(6).alwaysEat().saturationMod(tier1).effect(() -> new MobEffectInstance(MobEffects.NIGHT_VISION, 300), 1).effect(() -> new MobEffectInstance(MobEffects.DIG_SPEED, 100, 1), 1).build())));
    public static final RegistryObject<Item> COPPER_CARROT = ITEMS_R.register("copper_carrot", () -> new Item(new Item.Properties().tab(ModMain.CREATIVE_TAB).food(new FoodProperties.Builder().nutrition(6).alwaysEat().saturationMod(tier1).effect(() -> new MobEffectInstance(MobEffects.MOVEMENT_SPEED, 300, 1), 1).effect(() -> new MobEffectInstance(MobEffects.WEAKNESS, 100), 1).build())));
    public static final RegistryObject<Item> EMERALD_CARROT = ITEMS_R.register("emerald_carrot", () -> new Item(new Item.Properties().tab(ModMain.CREATIVE_TAB).food(new FoodProperties.Builder().nutrition(6).alwaysEat().saturationMod(tier1).effect(() -> new MobEffectInstance(MobEffects.HERO_OF_THE_VILLAGE, 100), 1).effect(() -> new MobEffectInstance(MobEffects.HEALTH_BOOST, 200), 1).build())));
    public static final RegistryObject<Item> LAPIS_CARROT = ITEMS_R.register("lapis_carrot", () -> new Item(new Item.Properties().tab(ModMain.CREATIVE_TAB).food(new FoodProperties.Builder().nutrition(7).alwaysEat().saturationMod(tier2).effect(() -> new MobEffectInstance(MobEffects.LUCK, 200), 1).effect(() -> new MobEffectInstance(MobEffects.DAMAGE_RESISTANCE, 300), 1).build())));
    public static final RegistryObject<Item> OBSIDIAN_CARROT = ITEMS_R.register("obsidian_carrot", () -> new Item(new Item.Properties().tab(ModMain.CREATIVE_TAB).food(new FoodProperties.Builder().nutrition(7).alwaysEat().saturationMod(tier1).effect(() -> new MobEffectInstance(MobEffects.DAMAGE_BOOST, 100, 0), 1).effect(() -> new MobEffectInstance(MobEffects.DAMAGE_RESISTANCE, 300, 0), 1).effect(() -> new MobEffectInstance(MobEffects.WATER_BREATHING, 100), 1).effect(() -> new MobEffectInstance(MobEffects.FIRE_RESISTANCE, 100), 1).build())));
    public static final RegistryObject<Item> DIAMOND_CARROT = ITEMS_R.register("diamond_carrot", () -> new Item(new Item.Properties().tab(ModMain.CREATIVE_TAB).food(new FoodProperties.Builder().nutrition(12).alwaysEat().saturationMod(tier3).effect(() -> new MobEffectInstance(MobEffects.REGENERATION, 400, 1), 1).effect(() -> new MobEffectInstance(MobEffects.DAMAGE_BOOST, 400, 1), 1).effect(() -> new MobEffectInstance(MobEffects.WATER_BREATHING, 600), 1).effect(() -> new MobEffectInstance(MobEffects.HEALTH_BOOST, 300, 1), 1).effect(() -> new MobEffectInstance(MobEffects.DAMAGE_RESISTANCE, 600, 1), 1).build())));
    public static final RegistryObject<Item> NETHERITE_CARROT = ITEMS_R.register("netherite_carrot", () -> new Item(new Item.Properties().tab(ModMain.CREATIVE_TAB).fireResistant().food(new FoodProperties.Builder().nutrition(20).alwaysEat().saturationMod(tier3).effect(() -> new MobEffectInstance(MobEffects.REGENERATION, 600, 2), 1).effect(() -> new MobEffectInstance(MobEffects.DAMAGE_BOOST, 600, 2), 1).effect(() -> new MobEffectInstance(MobEffects.FIRE_RESISTANCE, 600), 1).effect(() -> new MobEffectInstance(MobEffects.HEALTH_BOOST, 600, 2), 1).effect(() -> new MobEffectInstance(MobEffects.DAMAGE_RESISTANCE, 800, 2), 1).build())));
    public static final RegistryObject<Item> IRON_CARROT = ITEMS_R.register("iron_carrot", () -> new Item(new Item.Properties().tab(ModMain.CREATIVE_TAB).food(new FoodProperties.Builder().nutrition(7).alwaysEat().saturationMod(tier2).effect(() -> new MobEffectInstance(MobEffects.ABSORPTION, 200, 0), 1).effect(() -> new MobEffectInstance(MobEffects.REGENERATION, 200, 0), 1).effect(() -> new MobEffectInstance(MobEffects.DAMAGE_RESISTANCE, 600), 1).build())));
    public static final RegistryObject<Item> CREATIVE_CARROT = ITEMS_R.register("creative_carrot", () -> new Item(new Item.Properties().tab(ModMain.CREATIVE_TAB).food(new FoodProperties.Builder().nutrition(20).alwaysEat().saturationMod(tier3).effect(() -> new MobEffectInstance(MobEffects.REGENERATION, 2400, 7), 1).effect(() -> new MobEffectInstance(MobEffects.DAMAGE_BOOST, 2400, 7), 1).effect(() -> new MobEffectInstance(MobEffects.FIRE_RESISTANCE, 2400), 1).effect(() -> new MobEffectInstance(MobEffects.WATER_BREATHING, 2400), 1).effect(() -> new MobEffectInstance(MobEffects.HEALTH_BOOST, 2400, 2), 1).effect(() -> new MobEffectInstance(MobEffects.DAMAGE_RESISTANCE, 2400, 7), 1).build())));

    public static final RegistryObject<Item> COAL_NUGGET = ITEMS_R.register("coal_nugget", () -> new NuggetsItem(new Item.Properties().tab(ModMain.CREATIVE_TAB)));
    public static final RegistryObject<Item> COPPER_NUGGET = ITEMS_R.register("copper_nugget", () -> new NuggetsItem(new Item.Properties().tab(ModMain.CREATIVE_TAB)));
    public static final RegistryObject<Item> EMERALD_NUGGET = ITEMS_R.register("emerald_nugget", () -> new NuggetsItem(new Item.Properties().tab(ModMain.CREATIVE_TAB)));
    public static final RegistryObject<Item> LAPIS_NUGGET = ITEMS_R.register("lapis_nugget", () -> new NuggetsItem(new Item.Properties().tab(ModMain.CREATIVE_TAB)));
    public static final RegistryObject<Item> OBSIDIAN_NUGGET = ITEMS_R.register("obsidian_nugget", () -> new NuggetsItem(new Item.Properties().tab(ModMain.CREATIVE_TAB)));
    public static final RegistryObject<Item> DIAMOND_NUGGET = ITEMS_R.register("diamond_nugget", () -> new NuggetsItem(new Item.Properties().tab(ModMain.CREATIVE_TAB)));
    public static final RegistryObject<Item> NETHERITE_NUGGET = ITEMS_R.register("netherite_nugget", () -> new NuggetsItem(new Item.Properties().tab(ModMain.CREATIVE_TAB)));
}
